export const courseData = {
  METHOD_WORCURE: [
    {
      id: 0,
      title: 'MÓDULO 0: BEM-VINDO AO WORCURE',
      lessons: [
        { id: 1, title: 'O Que É o WORCURE e Por Que Funciona', content: `Você está diante de algo que pode mudar sua vida para sempre... Sua vida nunca mais será a mesma.` },
        { id: 2, title: 'Como Navegar no Portal WORCURE Members', content: `Você acabou de entrar no WORCURE Members... Próxima aula: a diferença entre MÉTODO e FLIX explicada em detalhes.` },
        { id: 3, title: 'A Diferença Entre MÉTODO WORCURE e WORCURE FLIX', content: `Deixa eu te fazer uma pergunta: você prefere receber um mapa do tesouro ou receber o tesouro direto na mão?... Próxima aula: o segredo do poder da palavra que muda tudo.` },
        { id: 4, title: 'O Segredo do Poder da Palavra', content: `Deixa eu te fazer uma pergunta que pode parecer estranha: o que veio primeiro, o homem ou a palavra?... Próxima aula: como funcionam os próximos doze módulos.` },
        { id: 5, title: 'Como Funcionam os Próximos Doze Módulos', content: `Você acabou de entender a base. Agora eu vou te mostrar COMO você vai aplicar isso nos próximos doze módulos... Paz Inabalável te espera.` },
      ],
    },
    {
      id: 1,
      title: 'MÓDULO 1: PAZ INABALÁVEL',
      lessons: [
        { id: 1, title: 'REVELAR A RAIZ DA ANSIEDADE', content: `Você acorda às três da manhã com o coração disparado... Próxima aula: como reprogramar isso com a Palavra de Deus.` },
        { id: 2, title: 'REPROGRAMAR COM A PALAVRA', content: `Expor a mentira é poderoso. Mas não é suficiente... Próxima aula: como recriar sua rotina de paz com o WORCURE FLIX.` },
        { id: 3, title: 'RECRIAR SUA ROTINA DE PAZ', content: `Você revelou a mentira. Você reprogramou com a verdade... Nos vemos lá.` },
      ],
    },
    {
      id: 2,
      title: 'MÓDULO 2: LIBERDADE FINANCEIRA',
      lessons: [
        { id: 1, title: 'REVELAR A RAIZ DA ESCASSEZ', content: `Você olha pro extrato bancário e sente o estômago revirar... Próxima aula: como reprogramar isso com a Palavra de Deus.` },
        { id: 2, title: 'REPROGRAMAR COM A PALAVRA', content: `Expor a mentira financeira é poderoso... Próxima aula: como recriar sua rotina financeira com o WORCURE FLIX.` },
        { id: 3, title: 'RECRIAR SUA ROTINA FINANCEIRA', content: `Você revelou a mentira. Você reprogramou com a verdade... Nos vemos lá.` },
      ],
    },
     {
      id: 3,
      title: 'MÓDULO 3: LAR RESTAURADO',
      lessons: [
        { id: 1, title: 'REVELAR A RAIZ DO CONFLITO', content: `Você chega em casa depois de um dia exaustivo... Próxima aula: como reprogramar isso com a Palavra de Deus.` },
        { id: 2, title: 'REPROGRAMAR COM A PALAVRA', content: `Expor os padrões destrutivos é poderoso... Próxima aula: como recriar sua rotina no lar com o WORCURE FLIX.` },
        { id: 3, title: 'RECRIAR SUA ROTINA NO LAR', content: `Você revelou a mentira. Você reprogramou com a verdade... Nos vemos lá.` },
      ],
    },
    {
      id: 4,
      title: 'MÓDULO 4: CURA PROFUNDA',
      lessons: [
        { id: 1, title: 'REVELAR A RAIZ DAS FERIDAS', content: `Tem uma dor dentro de você que ninguém vê... Próxima aula: como reprogramar isso com a Palavra de Deus e curar de verdade.` },
        { id: 2, title: 'REPROGRAMAR COM A PALAVRA', content: `Expor a ferida é doloroso. Mas é o primeiro passo... Próxima aula: como recriar sua rotina de cura com o WORCURE FLIX.` },
        { id: 3, title: 'RECRIAR SUA ROTINA DE CURA', content: `Você revelou as feridas. Você reprogramou com perdão... Nos vemos lá.` },
      ],
    },
    {
      id: 5,
      title: 'MÓDULO 5: ESPERANÇA REVIVIDA',
      lessons: [
        { id: 1, title: 'REVELAR A RAIZ DO DESÂNIMO', content: `Você acorda e não quer sair da cama... Próxima aula: como reprogramar isso com a Palavra de Deus.` },
        { id: 2, title: 'REPROGRAMAR COM A PALAVRA', content: `Expor o desânimo é doloroso. Mas necessário... Próxima aula: como recriar sua rotina de esperança com o WORCURE FLIX.` },
        { id: 3, title: 'RECRIAR SUA ROTINA DE ESPERANÇA', content: `Você revelou o desânimo. Você reprogramou com esperança... Nos vemos lá.` },
      ],
    },
    {
      id: 6,
      title: 'MÓDULO 6: VIDA VIBRANTE',
      lessons: [
        { id: 1, title: 'REVELAR A RAIZ DA EXAUSTÃO', content: `Você acorda cansado. Mesmo depois de oito horas de sono... Próxima aula: como reprogramar isso com a Palavra de Deus.` },
        { id: 2, title: 'REPROGRAMAR COM A PALAVRA', content: `Expor a exaustão é necessário. Mas não é suficiente... Próxima aula: como recriar sua rotina vibrante com o WORCURE FLIX.` },
        { id: 3, title: 'RECRIAR SUA ROTINA VIBRANTE', content: `Você revelou a exaustão. Você reprogramou com sabedoria... Nos vemos lá.` },
      ],
    },
    {
      id: 7,
      title: 'MÓDULO 7: LIBERDADE CONQUISTADA',
      lessons: [
        { id: 1, title: 'REVELAR A RAIZ DOS VÍCIOS', content: `Você promete que é a última vez. Você jura que nunca mais... Próxima aula: como reprogramar isso com o poder de Deus.` },
        { id: 2, title: 'REPROGRAMAR COM A PALAVRA', content: `Expor o vício é doloroso. Mas é o começo da liberdade... Próxima aula: como recriar sua rotina de liberdade com o WORCURE FLIX.` },
        { id: 3, title: 'RECRIAR SUA ROTINA DE LIBERDADE', content: `Você revelou o vício. Você reprogramou com poder... Nos vemos lá.` },
      ],
    },
    {
      id: 8,
      title: 'MÓDULO 8: BLINDAGEM ESPIRITUAL',
      lessons: [
        { id: 1, title: 'REVELAR A RAIZ DA VULNERABILIDADE', content: `Você sente que algo te ataca. Mas você não vê... Próxima aula: como reprogramar com blindagem bíblica.` },
        { id: 2, title: 'REPROGRAMAR COM A PALAVRA', content: `Expor a vulnerabilidade é necessário. Mas não é suficiente... Próxima aula: como recriar sua rotina de proteção com o WORCURE FLIX.` },
        { id: 3, title: 'RECRIAR SUA ROTINA DE PROTEÇÃO', content: `Você revelou a vulnerabilidade. Você reprogramou com armadura... Nos vemos lá.` },
      ],
    },
    {
      id: 9,
      title: 'MÓDULO 9: PROPÓSITO REVELADO',
      lessons: [
        { id: 1, title: 'REVELAR A RAIZ DA DESORIENTAÇÃO', content: `Você acorda todo dia e faz as mesmas coisas... Próxima aula: como reprogramar e VIVER seu propósito.` },
        { id: 2, title: 'REPROGRAMAR COM A PALAVRA', content: `Expor a desorientação é necessário. Mas não é suficiente... Próxima aula: como recriar sua rotina de chamado com o WORCURE FLIX.` },
        { id: 3, title: 'RECRIAR SUA ROTINA DE CHAMADO', content: `Você revelou as pistas. Você reprogramou com direção... Nos vemos lá.` },
      ],
    },
    {
      id: 10,
      title: 'MÓDULO 10: CONEXÃO VITAL',
      lessons: [
        { id: 1, title: 'REVELAR A RAIZ DA DISTÂNCIA', content: `Você ora. Mas parece que suas palavras batem no teto e voltam... Próxima aula: como reprogramar sua vida devocional.` },
        { id: 2, title: 'REPROGRAMAR COM A PALAVRA', content: `Expor a distância é doloroso. Mas necessário... Próxima aula: como recriar sua rotina de conexão com o WORCURE FLIX.` },
        { id: 3, title: 'RECRIAR SUA ROTINA DE CONEXÃO', content: `Você revelou a distância. Você reprogramou com disciplina... Nos vemos lá.` },
      ],
    },
    {
      id: 11,
      title: 'MÓDULO 11: DESVENDANDO A PALAVRA',
      lessons: [
        { id: 1, title: 'REVELAR A RAIZ DA CONFUSÃO', content: `Você abre a Bíblia. E não entende nada... Próxima aula: como reprogramar sua forma de ler a Bíblia.` },
        { id: 2, title: 'REPROGRAMAR COM A PALAVRA', content: `Expor as barreiras é necessário. Mas não é suficiente... Próxima aula: como recriar sua rotina de estudo com o WORCURE FLIX.` },
        { id: 3, title: 'RECRIAR SUA ROTINA DE ESTUDO', content: `Você revelou as barreiras. Você reprogramou com método... Nos vemos lá.` },
      ],
    },
    {
      id: 12,
      title: 'MÓDULO 12: FÉ PRÁTICA E IMPACTO',
      lessons: [
        { id: 1, title: 'REVELAR A RAIZ DA INÉRCIA', content: `Você conhece a Bíblia. Você ora. Você vai na igreja... Próxima aula: como reprogramar e VIVER com impacto.` },
        { id: 2, title: 'REPROGRAMAR COM A PALAVRA', content: `Expor a inércia é necessário. Mas não é suficiente... Próxima aula: como recriar sua rotina de serviço com o WORCURE FLIX.` },
        { id: 3, title: 'RECRIAR SUA ROTINA DE IMPACTO', content: `Você revelou a inércia. Você reprogramou com missão... A Palavra que Vive em Você.` },
      ],
    },
  ],
  WORCURE_FLIX: [
    {
      id: 1,
      title: 'Paz Inabalável',
      tags: ['ansiedade', 'medo', 'pânico', 'sono', 'paz', 'preocupação', 'decisões', 'futuro'],
      modules: [
        { id: 1, title: 'Respire e Ore: Filipenses 4 em Ação Para a Sua Alma' },
        { id: 2, title: 'SOS Pânico: 3 Minutos de Alívio na Palavra (Sl 56:3)' },
        { id: 3, title: 'Não Temas: A Promessa Divina que Acalma seu Coração (Is 41:10)' },
        { id: 4, title: 'A Paz de Cristo: Seu Refúgio Interior e Inabalável (Jo 14:27)' },
        { id: 5, title: 'Coração Sóbrio: Ativando o Espírito de Poder e Equilíbrio (2Tm 1:7)' },
        { id: 6, title: 'Tempestade Acalmada: A Voz de Jesus Trazendo Calma ao Caos (Mt 8)' },
        { id: 7, title: 'Durma em Paz: O Ritual Noturno que Desliga a Ansiedade (Sl 4:8)' },
        { id: 8, title: 'Fim do Terror Noturno: Promessas de Proteção Divina para Suas Noites (Sl 91)' },
        { id: 9, title: 'Sono Restaurador: Noites Tranquilas e Mente Serena (Pv 3:24)' },
        { id: 10, title: 'Desconecte a Mente: Lance Suas Preocupações em Deus (1Pe 5:7)' },
        { id: 11, title: 'Manhã Sem Ansiedade: Comece o Dia com as Prioridades do Reino (Mt 6)' },
        { id: 12, title: 'Viva Um Dia de Cada Vez: A Estratégia Bíblica Contra a Antecipação (Mt 6:34)' },
        { id: 13, title: 'Graça Para Hoje: As Misericórdias Novas de Cada Manhã (Lm 3:22-23)' },
        { id: 14, title: 'Blindagem de Notícias: Firme o Coração Contra o Alarmismo (Sl 112:7)' },
        { id: 15, title: 'Diagnóstico Assustador: Consolo e Coragem Bíblica Imediatos (Is 53 & Sl 23)' },
        { id: 16, title: 'Futuro em Paz: Deus Guia Cada Passo Seu (Jr 29:11 & Mt 6)' },
        { id: 17, title: 'Medo da Morte: A Vitória de Cristo que Dissipa o Pavor (Jo 11 & 1Co 15)' },
        { id: 18, title: 'Coragem para Recomeçar: Vença o Medo de Falhar com Deus (Js 1:9)' },
        { id: 19, title: 'Liberte-se do \'Que Vão Pensar\': Confie no Senhor (Pv 29:25)' },
        { id: 20, title: 'Crise no Trabalho: Orações e Atitudes de Paz no Escritório (Cl 3 & Pv)' },
        { id: 21, title: 'Paz Financeira: Acalme o Medo por Provisão e Conteúdo (Mt 6 & Sl 37)' },
        { id: 22, title: 'Proteção em Cada Caminho: O Guarda Divino na Sua Saída e Entrada (Sl 121)' },
        { id: 23, title: 'Preocupação com Filhos: Intercessão Objetiva e Segurança (Sl 127 & Pv)' },
        { id: 24, title: 'Pós-Reunião: Filtre Pensamentos Intrusivos com a Palavra (Fp 4:8)' },
        { id: 25, title: 'Corpo Sente o Medo: Ancoragem Bíblica para Sintomas Físicos (Sl 46)' },
        { id: 26, title: 'Calma em Conversas Difíceis: Confiança Que Desarma o Conflito (Sl 27)' },
        { id: 27, title: 'Oásis de Silêncio: 10 Minutos para Recarregar a Alma em Deus (Mc 1:35)' },
        { id: 28, title: 'Respire e Restaure: O Salmo 23 como Guia de Calma Profunda' },
        { id: 29, title: '21 Orações Expressas: Paz Instantânea para Momentos de Crise' },
        { id: 30, title: 'Declarações de Paz: Substitua Pensamentos Ansiosos por Verdade Bíblica (Jo 14 & Fp 4)' },
        { id: 31, title: '7 Dias de Sossego: Seu Miniplano de Alívio Contínuo da Ansiedade' },
        { id: 32, title: '21 Dias de Liberdade: Estabilize Mente e Emoções com a Palavra' },
        { id: 33, title: 'Salmos para Toda Crise: Um Mapa Prático de Consolo Imediato' },
        { id: 34, title: 'Ansiedade Digital: O Filtro de Filipenses 4:8 para o Uso do Celular' },
        { id: 35, title: 'Ansiedade por Dinheiro: Oração e Ação para Contas e Boletos (Fp 4:6-7)' },
        { id: 36, title: 'Entregue Seus Fardos: Troque o Peso Pelo Jugo Leve de Jesus (Mt 11:28-30)' },
        { id: 37, title: 'Medo Noturno: Respostas Bíblicas aos Terrores da Madrugada (Sl 91:5)' },
        { id: 38, title: 'A Frase Certa na Hora do Susto: “No Dia em que Eu Temo…” (Sl 56:3)' },
        { id: 39, title: 'Paz em Ambientes Hostis: Leve a Calma Onde a Tensão Prevalece (Rm 12:18 & Mt 5:9)' },
        { id: 40, title: 'Timidez e Ansiedade Social: Sua Identidade Inabalável em Deus (Sl 139 & Êx 4)' },
        { id: 41, title: 'Decisões Sem Medo: Sabedoria Divina para o Próximo Passo Certo (Tg 1:5)' },
        { id: 42, title: 'Tempestade Familiar: Respostas Bíblicas para Conflitos que Geram Ansiedade (Ef 4 & Cl 3)' },
        { id: 43, title: 'Ancorado na Verdade: Dissolva Mentiras Internas que Alimentam o Pânico (Jo 8:32)' },
        { id: 44, title: 'Refúgio Presente: Socorro Bem Perto na Angústia (Sl 46:1)' },
        { id: 45, title: 'Deus Luta Por Você: Fique Quieto e Veja o Senhor Agir (Êx 14:14)' },
        { id: 46, title: 'Mente Guardada: Mantenha o Pensamento em Deus para Paz Contínua (Is 26:3)' },
        { id: 47, title: 'Escudo da Fé: Erguer a Proteção Contra os Dardos do Medo (Ef 6:16)' },
        { id: 48, title: 'Desapego Bíblico: Jogue Fora o Excesso Mental e Emocional (Hb 12:1)' },
        { id: 49, title: 'Ansiedade e Culpa Espiritual: A Graça que Liberta da Condenação (Rm 8:1)' },
        { id: 50, title: 'Encerramento Diário: Ritual Para Desativar Pensamentos Antes de Dormir (Sl 92:2)' },
        { id: 51, title: 'Paz nas Notícias: Como Consumir Acontecimentos Sem Ser Engolido (Sl 2 & Sl 46)' },
        { id: 52, title: 'Oração Travada: Deixe o Espírito Santo Interceder em Seu Favor (Rm 8:26)' },
        { id: 53, title: 'Vale da Sombra: Caminhe Sem Temer o Mal com o Bom Pastor (Sl 23:4)' },
        { id: 54, title: 'Esperança para o Amanhã: Abasteça o Coração de Fé e Alegria (Rm 15:13)' },
        { id: 55, title: 'Forças Novas: Troque o Cansaço por Ânimo Real e Duradouro (Sl 121 & Is 40:31)' },
        { id: 56, title: 'Pequenas Vitórias: Vencendo a Ansiedade com Passos Curtos e Consistentes (Fp 3:13-14)' },
        { id: 57, title: 'Guia "Não Se Preocupe": Checklist Bíblico para Drenar a Preocupação na Hora (Mt 6)' },
        { id: 58, title: 'Diário da Libertação: Escreva, Entregue e Descanse em Deus (1Pe 5:7)' },
        { id: 59, title: 'Bússola para Decisões: Deixe a Paz de Cristo Guiar Suas Escolhas (Cl 3:15)' },
        { id: 60, title: 'Clima de Paz: Transforme Ambientes Tensos com Sua Presença (Rm 12:18 & Mt 5:9)' },
      ],
    },
    {
      id: 2,
      title: 'Liberdade Financeira',
      tags: ['dinheiro', 'dívida', 'orçamento', 'provisão', 'investimento', 'cartão de crédito', 'economia', 'generosidade'],
      modules: [
        { id: 1, title: 'Liberdade das Dificuldades Financeiras: Roteiro Bíblico para Retomar o Controle (Pv 22:7)' },
        { id: 2, title: 'Orçamento Consciente: Planeje Suas Finanças com Sabedoria (Lc 14:28-30)' },
        { id: 3, title: 'Reserva de Paz: O Plano de José para Tempos de Crise (Gn 41)' },
        { id: 4, title: 'Cartão de Crédito com Propósito: Controle e Sabedoria (Pv 21:5)' },
        { id: 5, title: 'Onde Seu Dinheiro Vaza: Feche as Brechas Financeiras (Ag 1:6)' },
        { id: 6, title: 'Contentamento Genuíno: Paz Financeira sem Comparação (Fp 4:11-13)' },
        { id: 7, title: 'Provisão Abundante: Alinhe Suas Finanças ao Reino (Mt 6:25-34)' },
        { id: 8, title: 'Finanças Honradas: Priorize Deus e Multiplique a Generosidade (Pv 3:9-10; 2Co 9:7)' },
        { id: 9, title: 'Renda Transformada: Trabalhe com Excelência "Como ao Senhor" (Cl 3:23)' },
        { id: 10, title: 'Negocie e Pague: Saia da Opressão das Cobranças (Rm 13:8)' },
        { id: 11, title: 'Fiador Nunca Mais: Proteja Suas Finanças e Relações (Pv 6:1-5; 22:26-27)' },
        { id: 12, title: 'Adeus Compras por Impulso: O Checklist de Paz (Fp 4:6-7)' },
        { id: 13, title: 'Riqueza Sólida: Ganhe Dinheiro com Honestidade e Paciência (Pv 13:11)' },
        { id: 14, title: 'Integridade nos Negócios: Balanças Justas Abençoam Sua Casa (Pv 11:1)' },
        { id: 15, title: 'Multiplique Seus Talentos: Prudência e Propósito (Mt 25:14-30)' },
        { id: 16, title: 'Risco Controlado: Diversifique Investimentos com Sabedoria (Ec 11:2)' },
        { id: 17, title: 'Organize Renda Variável: Princípios para Autônomos (Pv 27:23-27)' },
        { id: 18, title: 'Paz Financeira no Casamento: Acordos e Metas para a União (Ef 4:2-3)' },
        { id: 19, title: 'Educação Financeira para Filhos: Caráter e Mordomia (Pv 22:6)' },
        { id: 20, title: 'Blindagem Contra Golpes: Discernimento Financeiro (Pv 14:15)' },
        { id: 21, title: 'Desemprego com Esperança: Portas Abertas e Diligência (Sl 37:25)' },
        { id: 22, title: 'Equilíbrio Mensal: Início do Mês Sem Aperto (Pv 30:8-9)' },
        { id: 23, title: 'Crédito Inteligente: Use com Propósito, Não com Dívida (Pv 22:7)' },
        { id: 24, title: 'Planeje com Humildade: Metas Financeiras Guiadas por Deus (Tg 4:13-15)' },
        { id: 25, title: 'Corte Custos Invisíveis: Enxergue e Economize (Pv 27:12)' },
        { id: 26, title: 'Negócio de Valor: Empreenda com Propósito e Generosidade (Pv 31; At 20:35)' },
        { id: 27, title: 'Defina Preços Justos: Lucro Limpo e Consciência em Paz (Pv 16:11)' },
        { id: 28, title: 'Cheque Especial Zero: Recomece Sua Jornada Financeira (Is 43:19)' },
        { id: 29, title: 'O Padrão 10-10-80: Guardar, Doar e Viver com Sabedoria (Pv 21:20)' },
        { id: 30, title: 'Empréstimos Familiares: Limites Saudáveis para Não Arruinar Relações (Pv 17:18)' },
        { id: 31, title: 'Fundo de Paz: Sua Reserva de Emergência para Crises (Gn 41; Pv 6:6-8)' },
        { id: 32, title: 'Saúde e Finanças: Organize Cuidados com Fé e Realismo (3Jo 2; Sl 23)' },
        { id: 33, title: 'Dignidade no Trabalho: O Fruto do Esforço Honesto (Pv 14:23)' },
        { id: 34, title: 'Livre-se do Amor ao Dinheiro: Paz para a Alma (1Tm 6:6-10)' },
        { id: 35, title: 'Plano de Quitação: Dívidas Zero com Esperança Renovada (Lm 3:22-23)' },
        { id: 36, title: 'Quebre o Ciclo do Consumismo: Sobriedade e Contentamento (1Jo 2:16)' },
        { id: 37, title: 'Consciência Tranquila: Regularize Suas Finanças Fiscais (Rm 13:1-7)' },
        { id: 38, title: 'Negócios Alinhados: Proteja-se de Alianças Prejudiciais (2Co 6:14)' },
        { id: 39, title: 'Legado Abençoado: Planeje o Futuro de Seus Filhos (Pv 13:22)' },
        { id: 40, title: 'Multiplicação no Pouco: Obediência que Abre Provisão (1Rs 17; 2Rs 4)' },
        { id: 41, title: 'Riqueza com Integridade: Não Venda Sua Alma por Ganho (Pv 23:4-5)' },
        { id: 42, title: 'Mordomia Prática: Compre Melhor e Evite Desperdício (Pv 31:14-16)' },
        { id: 43, title: 'Seu Dom, Suas Portas: Alinhe Talento e Serviço (Pv 18:16)' },
        { id: 44, title: 'Reconstrua Sua Reputação: Bom Nome Financeiro (Pv 22:1)' },
        { id: 45, title: 'Colheita Abundante: Persistência na Semeadura (Gl 6:7-9)' },
        { id: 46, title: 'Grandes Decisões Financeiras: Sabedoria e Conselho (Pv 15:22)' },
        { id: 47, title: 'Orçamento Generoso: Multiplicando Significado e Alegria (At 20:35; 2Co 9)' },
        { id: 48, title: 'Mês de Paz: Seu Roteiro para Contas em Ordem (Sl 90:12)' },
        { id: 49, title: 'Descanso Financeiro: Evite Erros e Decisões Ruins (Êx 20:8-11)' },
        { id: 50, title: 'Lucro com Responsabilidade: Reconheça a Fonte da Provisão (Dt 8:18)' },
        { id: 51, title: 'Risco Equilibrado: Diligência e Diversificação com Deus (Pv 21:5; Ec 11)' },
        { id: 52, title: '21 Dias de Abundância: Transforme Angústia em Provisão' },
        { id: 53, title: 'Boletos em Paz: 7 Passos para Organizar Suas Contas' },
        { id: 54, title: 'Salmo 37: Estabilidade Financeira em Tempos Difíceis' },
        { id: 55, title: 'Renda Extra com Propósito: Ideias e Valores (Pv 12:11; 31)' },
        { id: 56, title: 'Proteja-se de Golpes Digitais: Prudência Financeira (Pv 22:3)' },
        { id: 57, title: 'Dívida Zero: O Plano Bíblico para Sua Liberdade (Rm 13:8)' },
        { id: 58, title: 'Contas Maiores que Você: Fé e Direção Divina (2Cr 20:12)' },
        { id: 59, title: 'Celebre o Suficiente: Paz e Gratidão à Mesa (1Tm 6:8)' },
        { id: 60, title: 'Declare Provisão: A Palavra que Atrai a Bênção (Sl 23; Mt 6)' },
      ],
    },
    // ... all other divisions
  ],
};
